---
global:
  scrape_interval: 1s
  evaluation_interval: 1s

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093
      
rule_files:
- flink.rules.yml

scrape_configs:
- job_name: 'flink'
  static_configs:
  - targets: ['exporter:9160']
