{
 "title": "Flink Dashboards",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Active Task Managers",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "flink_overview_taskmanagers" }
   ]
  },
  {
   "title": "Available Task Slots",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "flink_overview_slots_available" }
   ]
  },
  {
   "title": "List Running Job",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "flink_job_status_running" }
   ]
  },
  {
   "title": "Running Jobs",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "flink_job_status_running" }
   ]
  },
  {
   "title": "Failed Jobs",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "flink_overview_jobs_failed" }
   ]
  },
  {
   "title": "Flink Jobs - Write Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "flink_write_bytes", "legendFormat": "{{jobName}}" }
   ]
  },
  {
   "title": "Flink Jobs - Read Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "flink_read_bytes", "legendFormat": "{{jobName}}" }
   ]
  }
 ]
}